### PR TITLE
Compile with netgo to enable DNS resolution

### LINKED ISSUE #39: DNS resolution is failing in the container
Since the container is FROM scratch and the binaray is statically linked, DNS resolution with CoreDNS inside the cluster won't work.
From the build:
```
/usr/bin/ld: /tmp/go-link-262298860/000016.o: in function `_cgo_26061493d47f_C2func_getaddrinfo':
/tmp/go-build/cgo-gcc-prolog:58: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```

This makes the `--kubeconfig` flag unusable when there is a DNS name from within the cluster.

Would you be open to swtich the image to Alpine instead for instance?

### PR DESCRIPTION
**Pull request by Sh4d1**
Signed-off-by: Patrik Cyvoct <patrik@ptrk.io>

Fixes #39

### CODE REVIEW

**Comment by Sh4d1** [comment]
/assign @maciaszczykm
Could we release a new version if this gets merged?

**Comment by Sh4d1** [comment]
@jeefy can it be merged? Or waiting for another review? :)

**Comment by jeefy** [comment]
/lgtm 
I usually give courtesy time before I both lgtm and approve in case someone else has an opinion :)

**Comment by Sh4d1** [comment]
Fair enough 😄 thanks! Will it be possible to cut a release with just this change ? 😄

**Pull request merged**
