### PR TITLE
Use buildx for cross-platform builds

### PR DESCRIPTION
**Pull request by tumberino**
Reopened to hopefully solve CLA issue.

Test build:
https://hub.docker.com/r/jamesnelson/metrics-scraper/tags

### CODE REVIEW

**Comment by tumberino** [comment]
I've opened a support ticket for EasyCLA as it should be setup so not sure what is wrong.

**Comment by maciaszczykm** [comment]
@jtumber-ibm Sometimes there are some problems with it. Can you also make sure that your commits are signed correctly?

**Comment by tumberino** [comment]
@maciaszczykm CLA done, apologies for the delay

**Comment by maciaszczykm** [comment]
@jtumber-ibm Sure, no worries. Thanks for the PR!

**Pull request merged**
