### PR TITLE
Unify command line flags with metrics-server

### LINKED ISSUE #8: refresh-interval vs metric-resolution
The scraper takes a `--refresh-interval` argument with the time in seconds as the value, while metrics-server takes `--metrics-resolution` with a time period ("30s", "1m", etc) as the value.

How should these two options be used together? Do we want to scrape statistics at 1x or 2x the frequency that the metrics server maintains them internally? Should the arguments be the same, and take a value in the same format (interval spec vs seconds)?

### LINKED ISSUE #9: Help text defaults unnecessary / inaccurate
The command-line argument defaults are duplicated in the help text, and are (at times) inaccurate.

```
Usage of /metrics-sidecar:
  -db-file string
        What file to use as a SQLite3 database. Defaults to ':memory:' (default ":memory:")
  -kubeconfig string
        absolute path to the kubeconfig file
  -max-window int
        Window of time you wish to retain records (in minutes). Defaults to '15' (default 15)
  -refresh-interval int
        Frequency (in seconds) to update the metrics database. Defaults to '5' (default 10)
```

### PR DESCRIPTION
**Pull request by brandond**
Fixes #8 and fixes #9.

### CODE REVIEW

**Comment by jeefy** [comment]
@brandond Please sign the [CNCF CLA](https://git.k8s.io/community/CLA.md#the-contributor-license-agreement) and let me know when you do. Once that's all clear I can merge this in. :) 

Thanks!

**Comment by brandond** [comment]
CLA is signed, let me fix the tests - sorry!

**Pull request merged**
